### ISSUE TITLE
Adding Module

### ISSUE THREAD

**Issue by jensstalder** [TomHAnderson/zf-oauth2-doctrine#11]
Should it be mentioned at installation or is this to obvious?

Module needs actually be loaded: `application.config.php`

```php
return array(
    'modules' => array(
       /* ...  */
       'ZF\OAuth2\Doctrine',
       /* ...  */
   )
)
```

**Comment by TomHAnderson** [comment]
Fixed in 85e732bd8148978fbd6dbbd2d704fa0ea66a8e78
