### ISSUE TITLE
Add to zfcampus proper

### ISSUE THREAD

**Issue by TomHAnderson** [TomHAnderson/zf-oauth2-doctrine#15]
Although this repo is still in pre-release it's becoming more stable and popular.  Today saw 25% of total downloads since 3/21.  

I'd like to clone the repo to zfcampus soon so I can have an upstream.  

@weierophinney @jguittard @ezimuel

**Comment by TomHAnderson** [comment]
I can hold off on this for a couple days.  I'm renaming the module and dropping planned support for ODM

**Comment by TomHAnderson** [comment]
With the release of 0.2.1 this module is considered stable and releasable.  I'd like to move it to zfcampus now.

**Comment by TomHAnderson** [comment]
Summary
-------------

When I last asked @weierophinney about bringing this to zfcampus proper he expressed the opinion that this adapter was not adaptable to multiple APIs.  I disagree and will still push for the inclusion of this repo to zfcampus.  There should be an edit to the ui to include OAuth2 Doctrine when this module is included.

A Test Case In PDO
--------------------------
 I've studied the implementation of zf-mvc-auth and these are the parts as I see them for PDO:

The map is used to specify each API's authentication (global config)
```
    'zf-mvc-auth' => array(
        'authentication' => array(
            'map' => array(
                'Api\\V1' => 'oauth2_pdo',
            ),
        ),
    )
```

The adapter is defined here in local config in my example
```
    'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'oauth2_pdo' => array(
                    'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
                    'storage' => array(
                        'adapter' => 'pdo',
                        'dsn' => 'mysql:dbname=should_be_doctrine;host=localhost',
                        'route' => '/oauth',
                        'username' => 'orm',
                        'password' => '',
                    ),
                ),
            ),
        ),
    ),
```

Because `'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',` we need the zf-oauth2 config:
```
    'zf-oauth2' => array(
        'storage' => 'ZF\\OAuth2\\Adapter\\PdoAdapter',
        'db' => array(
            'dsn_type' => 'PDO',
            'dsn' => 'mysql:dbname=should_be_doctrine;host=localhost',
            'username' => 'orm',
            'password' => '',
        ),
    ),
```


Configuring OAuth2 Doctrine
---------------------------------------

zf-oauth2-doctrine is an adapter for the zf-oauth2 (third) config only.  The config for zf-oauth2 when zf-oauth2-doctrine is used:
```
    'zf-oauth2' => array(
        'storage'        => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
    ),
```

Also needed is the oauth2.doctrine-orm.global.php(.dist) in this repo but nothing about zf-oauth2-doctrine is specific to only supporting a particularly one-only oauth2.


Caveat
---------

In my _use_ of zf-oauth2-doctrine I have been a proponent of manually validating the bearer token so the scope may be validated too through zf-apigility-doctrine Query Providers and Query Create Filters.


Conclusion
---------------

There is nothing in how zf-mvc-auth implements zf-oauth2 that zf-oauth2-doctrine manipulates or hinders in any way.  I request this repository be added to zfcampus.

**Comment by TomHAnderson** [comment]
Perhaps MWOP was referring to multiple `zf-oauth2` configurations.  In that case the zf-oauth2 config would be moved here:

```
'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'zf-oauth2-a' => array(
                    // zf-oauth2 config + zf-oauth2-doctrine config
                    'adapter' => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
...
```

Multiple zf-oauth2 configurations are not currently supported.

**Comment by weierophinney** [comment]
@TomHAnderson I was indeed refering to multiple OAuth2 configurations, which are provided via zf-mvc-auth. As long as you have a documented way of setting those up, we can proceed, but without those, this module does not integrate well with 1.1 and forwards.

**Comment by TomHAnderson** [comment]
While still a goal of mine and zfcampus I'll close this issue for now because we have no timeline.
