### ISSUE TITLE
Implicit flow implementation with authentication views

### ISSUE THREAD

**Issue by jackdpeterson** [TomHAnderson/zf-oauth2-doctrine#17]
Hello,
I'd like to integrate the implicit flow as part of my application's authentication strategy. That being said after chatting on IRC #apigility it appears that the authentication step is not yet implemented where a user object is stored in local session storage (or even as a doctrine session-object) to support the implicit grant strategy properly.

Steps to reproduce:
* in configuration (global.php)
```
 'zf-oauth2' => array(
        'storage' => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
        'allow_implicit' => true,
    )
```
* navigate to /oauth/authorize?client_id={SOME_CLIENT_ID}&response_type=token&state=abc
* click on Yes to authorize the client id.

Due to the lack of a complete authentication strategy for implicit grant I believe the following exception is generated:

File:
E:\Bitbucket\example\com.example.api\vendor\zfcampus\zf-oauth2-doctrine\src\Mapper\AbstractMapper.php:217

Message:
Relation was not found: user_id: 

Stack trace:
#0 E:\Bitbucket\example\com.example.api\vendor\zfcampus\zf-oauth2-doctrine\src\Adapter\DoctrineAdapter.php(540): ZF\OAuth2\Doctrine\Mapper\AbstractMapper->exchangeOAuth2Array(Array)
#1 E:\Bitbucket\example\com.example.api\vendor\bshaffer\oauth2-server-php\src\OAuth2\ResponseType\AccessToken.php(84): ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter->setAccessToken('7f12517e9ef734e...', 'com.example...', NULL, 1430422400, '')
#2 E:\Bitbucket\example\com.example.api\vendor\bshaffer\oauth2-server-php\src\OAuth2\ResponseType\AccessToken.php(55): OAuth2\ResponseType\AccessToken->createAccessToken('com.example...', NULL, '', false)
#3 E:\Bitbucket\example\com.example.api\vendor\bshaffer\oauth2-server-php\src\OAuth2\Controller\AuthorizeController.php(90): OAuth2\ResponseType\AccessToken->getAuthorizeResponse(Array, NULL)
#4 E:\Bitbucket\example\com.example.api\vendor\bshaffer\oauth2-server-php\src\OAuth2\Server.php(303): OAuth2\Controller\AuthorizeController->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), true, NULL)
#5 E:\Bitbucket\example\com.example.api\vendor\zfcampus\zf-oauth2\src\Controller\AuthController.php(169): OAuth2\Server->handleAuthorizeRequest(Object(OAuth2\Request), Object(OAuth2\Response), true, NULL)
#6 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): ZF\OAuth2\Controller\AuthController->authorizeAction()
#7 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(ZF\ContentNegotiation\Request), Object(Zend\Http\PhpEnvironment\Response))
#12 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#13 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 E:\Bitbucket\example\com.example.api\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 E:\Bitbucket\example\com.example.api\public\index.php(63): Zend\Mvc\Application->run()
#17 {main}

I would like to propose that an authentication strategy is implemented with a basic login screen (userid, password, remember me for N days)  [where N >= some configuration param] as well as a logout screen in this module to keep things cohesive.

My question to you is:  Do you think that this feature request belongs in this module?

Thanks!

**Comment by TomHAnderson** [comment]
The view layer for OAuth2 is handled in https://github.com/zfcampus/zf-oauth2/tree/master/view/zf/auth
The goal of this repository is to provide an OAuth2 ORM Adapter.  The ability to handle allow_implicit falls back to https://github.com/bshaffer/oauth2-server-php and the gist is this is an adapter for that class.

So allow_implicit view layer should be part of zf-oauth2
