### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by juizmill** [TomHAnderson/zf-oauth2-doctrine#2]
[https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/Module.php#L6](https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/Module.php#L6)

**UserClientSubscriber**  does not exist

**Comment by TomHAnderson** [comment]
@juizmill Thanks for the interest!  This project isn't ready for use yet.  It was almost ready at one time then I broke it off into this separate project.  I'm building via TDT right now.

My goal is to have this working by next month.

**Comment by TomHAnderson** [comment]
Moved UserClientSubscriber over from old repo.  Tested in unit tests also pushed.
