### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by basz** [TomHAnderson/zf-oauth2-doctrine#23]
Whilst deleting a client a constant error is thrown if tokens exists, not sure if this is correct/intended behavior 

An exception occurred while executing 'DELETE FROM oauth2_client WHERE clientId = 'plhw-client'':

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`plhw_data`.`oauth2_refreshtoken`, CONSTRAINT `FK_5B5D887919EB6921` FOREIGN KEY (`client_id`) REFERENCES `oauth2_client` (`id`))

same is true for oauth2_accesstoken...

adding 'on-delete="CASCADE"' on the join Column definitions fixes it

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/TomHAnderson/zf-oauth2-doctrine/pull/26
