### ISSUE TITLE
Problem command orm:schema-tool:update

### ISSUE THREAD

**Issue by juizmill** [TomHAnderson/zf-oauth2-doctrine#3]
When you run the command **orm:schema-tool:update** as mapping generates this error:

```
  [Doctrine\Common\Persistence\Mapping\MappingException]  
  Class 'ZF\OAuth2\Entity\AccessToken' does not exist 
```

**Comment by TomHAnderson** [comment]
The unit tests now in place use the schema generator.  This repo isn't designed to have orm:schema-tool support though the console.  Because the schema generator works though the unit tests I'll close this issue now.
