### ISSUE TITLE
Names of entities

### ISSUE THREAD

**Issue by juizmill** [TomHAnderson/zf-oauth2-doctrine#32]
Today the entities are the names with capital letters https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/media/OAuth2-orm.module.xml#L14

To follow good standards'd better leave with lowercase letters.

**Comment by juizmill** [comment]
Today the entities are the names with capital letters https://github.com/TomHAnderson/zf-oauth2-doctrine/blob/master/media/OAuth2-orm.module.xml#L14

To follow good standards'd better leave with lowercase letters.

**Comment by TomHAnderson** [comment]
The ERD _is_ the best standard.  Entity names start with upper case and fields start with lower case.  That's very good.  The table names match the entity names so the difference between knowing the schema in the database and knowing the schema in the ORM is minimal.  That's very good.  

Each Entity in the ERD, which is the metadata, corresponds to a class name and per PSR-1: "Class names MUST be declared in StudlyCaps."

If you know of better standards which extend from the PSR standards I'm open to hearing specific ideas.

**Comment by TomHAnderson** [comment]
Also https://github.com/basz/zf-oauth2-doctrine-mutatetablenames does what I think you're requesting.
