### ISSUE TITLE
Support zfcampus/zf-mvc-auth 1.3+

### ISSUE THREAD

**Issue by TomHAnderson** [TomHAnderson/zf-oauth2-doctrine#40]
Modify this module to work as storage for from a service.  This will allow multiple OAuth2 installations per Apigility installation allowing for multiple installations per API.

**Comment by TomHAnderson** [comment]
Doctrine OAuth2 adapters will be configured like:

```php
'zf-mvc-auth' => [
    'authentication' => [
        'map' => [
            'Api\\V1' => 'oauth2_doctrine',
        ],
    ],
],

'zf-mvc-auth' => [
    'authentication' => [
        'adapters' => [
            'oauth2_doctrine' => [
                'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
                'storage' => [
                    'default' => 'oauth2.doctrineadapter.default',
                ],
            ],
        ],
    ],
],
```

**Comment by TomHAnderson** [comment]
Testing (comment in progress):

```
composer create-project -sdev zfcampus/zf-apigility-skeleton zf-oauth2-doctrine-test ^1.3
composer require zfcampus/zf-oauth2-doctrine dev-master#1d0859cb60e52d1fb33b7fb6c2fc1d8f9b83e087
cp vendor/zfcampus/zf-oauth2-doctrine/config/oauth2.doctrine-orm.global.php.dist ./config/autoload/oauth2.doctrine-orm.global.php
```

**Comment by JimmyPHP** [comment]
Thank you Tom.

When I use the above config exactly the same, with the exception of changing API\\V1 to MyAPIName\V1, I get an exception on every apigility page:

>Missing or invalid storage adapter information for OAuth2	
>OAuth2ServerFactory.php:71
>2	Error	Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotCreatedException' with message 'Missing or invalid storage adapter information for OAuth2' in /usr/local/zend/

Do I need to define oauth2.doctrineadapter.default somehow? 

Background:
oauth2.doctrine-orm.global.php has been modified to point to my custom user entity. I successfully ran the doctrine-module schema create and the database is working.

**Comment by JimmyPHP** [comment]
Forgive my confusion, maybe that is only if we need to have multiple adapters? I believe I'm very close but not sure how to actually use this module as an adapter. I've tried a few different versions of code with the above. Also, if I simply put
>
  'zf-oauth2' => array(
        'storage'        => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
    )

In local.php, I get:
>
 The authentication adapter specified doesn't exist

Thanks for any guidance.

**Comment by TomHAnderson** [comment]
@weierophinney, @ezimuel I have rewritten this module to act as a storage for OAuth2.  The working branch and documentation for integration with zf-mvc-auth is is https://github.com/TomHAnderson/zf-oauth2-doctrine/tree/feature/zf-mvc-auth#configuration-with-zf-mvc-auth

I have created a skeleton branch for testing.  I didn't know how far to take this branch and if more is needed just let me know.  This txt file is a walkthrough on the skeleton branch to duplicate my work:  https://github.com/TomHAnderson/zf-apigility-skeleton/blob/skeleton/zf-oauth2-doctrine/zf-oauth2-doctrine.txt

Please review these two documents and let me know what more I can add to them to ease testing or move forward with testing.

**Comment by TomHAnderson** [comment]
This works from version 1.0.0
