### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by viniciusgava** [TomHAnderson/zf-oauth2-doctrine#42]
Hello, First of all, thank you for this module, I was seeking a project like this.
I am beginner in apigility I am trying to configure a project to work with apigility, doctrine and oauth.
I add the project to composer, copy the configuration(oauth2.doctrine-orm.global.php) to autoload and change it to my user entity. I add too the modules too.
When I browser to localhost:8888/oauth I receive this message:
```
The storage configuration for OAuth2 is missing
```

I don't know what is wrong.

**local.php**
```php
return array(
    'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'zf-oauth2-doctrine' => array(
                    'adapter' => 'ZF\\OAuth2\\Doctrine\\Adapter\\DoctrineAdapter',
                ),
            ),
        ),
    ),
);
```

**global.php**
```php
$userEntity = 'Rick\Common\Entity\User';

return array(
    'zf-oauth2-doctrine' => array(
        'storage' => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
        'storage_settings' => array(
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'event_manager' => 'doctrine.eventmanager.orm_default',
            'driver' => 'doctrine.driver.orm_default',
            'enable_default_entities' => true,
            'bcrypt_cost' => 14, # match zfcuser
            'auth_identity_fields' => array('email','document'),
            // Dynamically map the user_entity to the client_entity
            'dynamic_mapping' => array(
                'user_entity' => array(
                    'entity' => $userEntity,
                    'field' => 'user',
                ),
.
.
.
```

application.config.php
```php
return array(
    'modules' => array(
        'Rick\\Site',
        'Rick\\Common',
        'ZendDeveloperTools',
        'DoctrineModule',
        'DoctrineORMModule',
        'ZF\\Apigility',
        'ZF\\Apigility\\Provider',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\MvcAuth',
        'ZF\\OAuth2',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'ZF\\DevelopmentMode',
        'Phpro\\DoctrineHydrationModule',
        'ZF\\Apigility\\Doctrine\\Server',
        'ZF\\OAuth2\\Doctrine',
        'ZF\\OAuth2\\Doctrine\\MutateTableNames',
        'RickClientApi',
    ),
```

Thank you!

**Comment by TomHAnderson** [comment]
See https://github.com/zfcampus/zf-oauth2/issues/117

Also, the oauth2.doctrine config file has changed. zf-oauth2-doctrine is not supported in dev-master at this time because of the bug you reported also reported as 117, but you may use the doctrine-skeleton repo listed in 117 for more details.

**Comment by viniciusgava** [comment]
Hello @TomHAnderson , but without this fix it is not possible to make the oauth with doctrine work in the dev-master?

**Comment by TomHAnderson** [comment]
See the releases for a version which might work: https://github.com/TomHAnderson/zf-oauth2-doctrine/releases

There have been major changes to how OAuth2 adapters like this one are handled in Apigility.  I would appreciate it if you'd post also in https://github.com/zfcampus/zf-oauth2/issues/117 to bring more attention to the issue.

**Comment by TomHAnderson** [comment]
Fixed; see README.md for more configuration.
