### ISSUE TITLE
DynamicMappingSubscriber: Argument #2 is not an array and error to get $clientIdField 

### ISSUE THREAD

**Issue by viniciusgava** [TomHAnderson/zf-oauth2-doctrine#45]
Hello, I got some errors in the DynamicMappingSubscriber.

Errors because argument two is not a array:

**\ZF\OAuth2\Doctrine\EventListener\DynamicMappingSubscriber:143**
from this
````php
$this->getConfig()->refresh_token_entity->additional_mapping_data
````
to this
````php
$this->getConfig()->refresh_token_entity->additional_mapping_data->toArray()
````
**\ZF\OAuth2\Doctrine\EventListener\DynamicMappingSubscriber:128**
from this
````php
$this->getConfig()->authorization_code_entity->additional_mapping_data
````
to this
````php
$this->getConfig()->authorization_code_entity->additional_mapping_data->toArray()
````
**\ZF\OAuth2\Doctrine\EventListener\DynamicMappingSubscriber:98**
from this
````php
$this->getConfig()->client_entity->additional_mapping_data
````
to this
````php
$this->getConfig()->client_entity->additional_mapping_data->toArray()
````
I got a error too in this line:
**\ZF\OAuth2\Doctrine\EventListener\DynamicMappingSubscriber:83**
````php
$clientIdField = $this->getMapping()->Client->mapping->client_id->name;
````
I solve here with this:
````php
$clientIdField = $this->getMapping()->{'ZF\OAuth2\Doctrine\Mapper\Client'}->mapping->client_id->name;
````
I do not send you a pull request because these fixes require changes in the tests too.

**Comment by viniciusgava** [comment]
The problems in the mapping have more classes with the same problem, I imagine this problem is in the config file and does not in the source, does it?
Example:
src/Adapter/DoctrineAdapter.php:307
````php
$this->getConfig()->mapping->Client->mapping->client_id->name;
````

**Comment by svengraziani** [comment]
Same behavoiur here. thx @viniciusgava your fixes did the job

**Comment by viniciusgava** [comment]
Hello @svengraziani thank you by feedback. 
I opened a pull request about this issue.
https://github.com/TomHAnderson/zf-oauth2-doctrine/pull/46

**Comment by viniciusgava** [comment]
Problem solved and already in the master branch.
