### ISSUE TITLE
Adapter not recognized by Apigility

### ISSUE THREAD

**Issue by DevDev1** [TomHAnderson/zf-oauth2-doctrine#48]
Hi there,

Here is what I want to accomplish - I want to make OAuth2 process working with ZfcUser (+ZfcRbac: https://github.com/remiq/apigility-zfc-rbac-recipe  : did not get to that step yet - I need to have working authentication process using Doctrine ORM; I believe this is what your module do-or will help to do) and to be able to do authentication/authorization on my API - curently testing with StatusLib REST example

Until now, I can POST json with zfcuser email/pass combination to /oauth and I'm able to get Bearer token (using password grant type - my json looks like this
```
{
"grant_type":"password",
"client_id":"testclient",
"username":"test@test.com",
"password":"testpass"
}
```

I'm using
```'auth_identity_fields' => array('email'),```

didn't get it work with ```'auth_identity_fields' => array('username','email'),```

and i also had to modify mapping for user (added email)
```
'mapping' => array(
                'User' => array(
                    'entity' => $userEntity,
                    'mapping' => array(
                        'user_id' => array(
                            'type' => 'field',
                            'name' => 'id',
                            'datatype' => 'integer',
                        ),
                        'username' => array(
                            'type' => 'field',
                            'name' => 'username',
                            'datatype' => 'string',
                        ),
						// Added email 
						'email' => array(
                            'type' => 'field',
                            'name' => 'email',
                            'datatype' => 'string',
                        ),
                        'password' => array(
                            'type' => 'field',
                            'name' => 'password',
                            'datatype' => 'string',
                        ),
                    ),
                ),
```

Now problem is when I enable authorization, and set 
```
'zf-mvc-auth' => array(
        'authentication' => array(
            'map' => array(
                'DbApi\\V1' => 'oauth2_doctrine',
				'Status\\V1' => 'oauth2_doctrine',
```

that if I try to access my resource /status with token in Authorization header I got response Forbiden.
Also in Apigility admin ui - under Authenticatoin tab there is Error fetching authentication adapters
I managed to view response from where it comes (see attached images)
![1](https://cloud.githubusercontent.com/assets/13062559/9799705/444fd9cc-5809-11e5-8314-1655b2cb3469.jpg)
![2](https://cloud.githubusercontent.com/assets/13062559/9799706/44729b7e-5809-11e5-9ec2-dcd2aa550716.jpg)

```
Notice: Undefined index: adapter
Notice: Undefined index: dsn
```

I believe it is related to this piece of code:
```
'zf-mvc-auth' => array(
        'authentication' => array(
            'adapters' => array(
                'oauth2_doctrine' => array(
                    'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
					// 'adapter' => 'oauth2.doctrineadapter.default',
                    'storage' => array(
                        'storage' => 'oauth2.doctrineadapter.default',
                        'route' => '/oauth',
						//'dsn' => '',
						/*'adapter' => 'pdo',
                        'dsn' => 'mysql:host=localhost;dbname=apigility',
                        'username' => 'root',
                        'password' => '123',*/
                    ),		
                ),
            ),
        ),
    ),
```
Maybe something about   'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter', ??

If I put 'adapter' => 'oauth2.doctrineadapter.default',  Apigility Admin can see it, but still I'm getting Forbiden when accessing /status with token

Do you have any idea what I'm missing or doing wrong?

**Comment by DevDev1** [comment]
Ok, I think I resolve it.

Problem was in vagrant how it manages Authorization token; if in FastCGI - token when posted in Authorization header do not get to apigility (do not pass throug appache)

setting in .htaccess (at beginning just after RewriteEngine On):
```
RewriteCond %{HTTP:Authorization}  ^(.*)
RewriteRule ^(.*)$ $1 [e=HTTP_AUTHORIZATION:%1]
```

solved my issue, now I can access my test StatusLib rest resource with Bearer token

Hope this info will help (maybe put it in Tip&Tricks in readme?)

But there are still errors in Apigility Admin ui (when navigate to Authentication tab) - is that Ok? will be solved?

**Comment by TomHAnderson** [comment]
These are questions for the zfcampus set of repositories.  I am not part of the UI project but if you become involved that would certainly make the project better.

As for your vagrant, this repo does not have a Vagrantfile so that's really outside the scope of this project.
