### ISSUE TITLE
Configuration of name of configuration

### ISSUE THREAD

**Issue by hlogeon** [TomHAnderson/zf-oauth2-doctrine#49]
I have been trying to implement zf-oauth2-doctrine and zf-oauth2-doctrine-mutatetablenames
but when it's came to use it I found out that "zf-oauth2-doctrine-mutatetablenames" module expects 'zf-oauth2-doctrine' config will have "storage_settings" key with exactly same data as in your docs in "default" section. So, when I change "default" to required, your module shows me error that the key "default" doesn't exists. Of course, I can have both keys, bu it's not a good way to solve this problem. Could you tell me what am I doing wrong?

**Comment by TomHAnderson** [comment]
This belongs on the mutatetablenames and a PR to fix it there would be appreciated.  https://github.com/TomHAnderson/zf-oauth2-doctrine/releases/tag/0.3.5 was the last version which mutatetablenames worked with.
