### ISSUE TITLE
documentation request surrounding module configuration

### ISSUE THREAD

**Issue by jackdpeterson** [TomHAnderson/zf-oauth2-doctrine#5]
First of all thanks for writing this module. I'm looking forward to using this! 

It seems like there's a missing step once the module is configured and entities are built out. How does one then use zf-oauth2-doctrine as the oauth authentication server?

If I don't have anything configured in local.php (auto-generated by apigility if I were to specify a PDO oauth adapter) then I get this exception when attempting to authenticate against /oauth:

An exception was raised while creating \"ZF\\OAuth2\\Controller\\Auth\"; no instance returned

Is there some additional configuration tidbits that need to be added to enable the oauth authentication URI, and appropriate handlers?

Thanks!

**Comment by juizmill** [comment]
Really not working, but going to **global.php** and add the following code works:

```
    'zf-oauth2' => array(
        'storage' => 'ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter',
    )
```

**Comment by jackdpeterson** [comment]
Well, that gets things one step further ...

Could not convert database value \"password\" to Doctrine Type array

\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Types\\ArrayType.php(60): Doctrine\\DBAL\\Types\\ConversionException::conversionFailed('password', 'array')\n#1


Stack trace:

#0 E:\Bitbucket\com.example.apigility\vendor\doctrine\dbal\lib\Doctrine\DBAL\Types\ArrayType.php(60): Doctrine\DBAL\Types\ConversionException::conversionFailed('password', 'array')
#1 E:\Bitbucket\com.example.apigility\vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator.php(128): Doctrine\DBAL\Types\ArrayType->convertToPHPValue('password', Object(Doctrine\DBAL\Platforms\MySqlPlatform))
#2 E:\Bitbucket\com.example.apigility\vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator.php(69): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData(Array, Array)
#3 E:\Bitbucket\com.example.apigility\vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\AbstractHydrator.php(147): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData()
#4 E:\Bitbucket\com.example.apigility\vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php(720): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#5 E:\Bitbucket\com.example.apigility\vendor\doctrine\orm\lib\Doctrine\ORM\EntityRepository.php(196): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, NULL, NULL, Array, NULL, 1, NULL)
#6 E:\Bitbucket\com.example.apigility\vendor\zfcampus\zf-oauth2-doctrine\src\Adapter\DoctrineAdapter.php(252): Doctrine\ORM\EntityRepository->findOneBy(Array)
#7 E:\Bitbucket\com.example.apigility\vendor\bshaffer\oauth2-server-php\src\OAuth2\ClientAssertionType\HttpBasic.php(57): ZF\OAuth2\Doctrine\Adapter\DoctrineAdapter->isPublicClient('testing')
#8 E:\Bitbucket\com.example.apigility\vendor\bshaffer\oauth2-server-php\src\OAuth2\Controller\TokenController.php(112): OAuth2\ClientAssertionType\HttpBasic->validateRequest(Object(OAuth2\Request), Object(OAuth2\Response))
#9 E:\Bitbucket\com.example.apigility\vendor\bshaffer\oauth2-server-php\src\OAuth2\Controller\TokenController.php(49): OAuth2\Controller\TokenController->grantAccessToken(Object(OAuth2\Request), Object(OAuth2\Response))
#10 E:\Bitbucket\com.example.apigility\vendor\bshaffer\oauth2-server-php\src\OAuth2\Server.php(252): OAuth2\Controller\TokenController->handleTokenRequest(Object(OAuth2\Request), Object(OAuth2\Response))
#11 E:\Bitbucket\com.example.apigility\vendor\zfcampus\zf-oauth2\src\Controller\AuthController.php(54): OAuth2\Server->handleTokenRequest(Object(OAuth2\Request))
#12 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(82): ZF\OAuth2\Controller\AuthController->tokenAction()
#13 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#14 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#15 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#16 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(ZF\ContentNegotiation\Request), Object(Zend\Http\PhpEnvironment\Response))
#18 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#20 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 E:\Bitbucket\com.example.apigility\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#22 E:\Bitbucket\com.example.apigility\public\index.php(51): Zend\Mvc\Application->run()
#23 {main}

**Comment by jackdpeterson** [comment]
Okay, so I figured the issue out with this:

setting the grantType field in the database to, 'password' causes this exception to appear.
Setting to null allows the authentication to proceed :-)

**Comment by TomHAnderson** [comment]
zf-oauth2-doctrine is an adapter for zf-oauth2 so the idea is you configure zf-oauth2 and zf-oauth2-doctrine.  

I suggest you pick up https://github.com/TomHAnderson/apigility-oauth2-doctrine-skeleton
This project is still in development but it implements zf-oauth2-doctrine.  There is a User entity already in place and you can create the database with orm:schema-tool:create

The next steps for this skeleton are user roles, console add administrator, Zfc-Admin working, and bjy-authorize restricted routes based on user roles.

**Comment by TomHAnderson** [comment]
The intention of this doctrine work is to have the database creation handled by the ORM.  And password is not a Doctrine field type.
