### ISSUE TITLE
apigility 1.1 compatibility issue?

### ISSUE THREAD

**Issue by jackdpeterson** [TomHAnderson/zf-oauth2-doctrine#7]
'An alias by the name "zfoauth2provideruserid" or "ZF\OAuth2\Provider\UserId" already exists'.

The issue is that the zf-oauth2-doctrine module redeclares this invokable and it is now in conflict with Apigility 1.1:

// zfcampus/zf-oauth2/config/module.config.php
'service_manager' => array(
        'aliases' => array(
            'ZF\OAuth2\Provider\UserId' => 'ZF\OAuth2\Provider\UserId\Request',
        ),
        'invokables' => array(
            'ZF\OAuth2\Provider\UserId\Request' => 'ZF\OAuth2\Provider\UserId\Request',
        ),
compare with
// zfcampus/zf-oauth2-doctrine/config/modulle.config.php

 'service_manager' => array(
        'invokables' => array(
            'ZF\OAuth2\Provider\UserId' => 
                'ZF\OAuth2\Provider\UserId\AuthenticationService',
        ),

Note that the key is the same for both. Re-declaring the same key is causing a fatal exception to be thrown.

**Comment by TomHAnderson** [comment]
I will listen to your question if you spend more time writing it than pasting code.  If you did in fact already read your pasted code please re-paste the section(s) you are having issues with.  

p.s. This library is not at a release state and I hope you'll find room to contribute to the module until we get there: https://github.com/TomHAnderson/zf-oauth2-doctrine/releases

**Comment by jackdpeterson** [comment]
See updated comment above. I provided the details earlier such a composer.lock and the doctrine oauth configuration (vanilla plus change to user entity referenced) to clearly define what version of each dependency was installed and to ensure that a complete bug report was provided.

**Comment by TomHAnderson** [comment]
You're right, @jackdpeterson This module is not the right place to configure the UserId Provider for zf-oauth2.  And I was doing it the old/wrong way!  Thanks for clarifying that.  I've got a section in the README now for how to configure the zf-oauth2 UserId Provider.
